### PR TITLE
Fix batching loading in mutation subselection

### PR DESCRIPTION
**Pull request by dylanahsmith**
Closes #30

@rmosolgo I added a regression test for the broken code you tried to remove in #30 and fixed it without swapping the execution strategy

@xuorig & @cjoudrey looks like our batching has been broken for mutations subselections which this fixes

### CODE REVIEW

**Comment by rmosolgo** [comment]
👏

File: lib/graphql/batch/mutation_execution_strategy.rb [hunk 1]
```diff
@@ -1,18 +1,18 @@
...
+  class MutationExecutionStrategy < GraphQL::Batch::ExecutionStrategy
+    class FieldResolution < GraphQL::Batch::ExecutionStrategy::FieldResolution
       def get_finished_value(raw_value)
+        return super if execution_context.strategy.disable_batching
+
         raw_value = GraphQL::Batch::Promise.resolve(raw_value).sync
 
-        context = execution_context.query.context
-        old_execution_strategy = context.execution_strategy
+        execution_context.strategy.disable_batching = true
```
Comment (dylanahsmith) [inline lib/graphql/batch/mutation_execution_strategy.rb]: looks like https://github.com/rmosolgo/graphql-ruby/pull/379 changed in https://github.com/rmosolgo/graphql-ruby/pull/379 so this no longer works in graphql-ruby now that 1.2 has been released (https://travis-ci.org/Shopify/graphql-batch/jobs/174014089).

GraphQL::BatchTest#test_mutation_batch_subselection_execution:
NoMethodError: undefined method `strategy' for #<GraphQL::Query::Context::FieldResolutionContext:0x00000002e23180>
    /home/travis/build/Shopify/graphql-batch/lib/graphql/batch/mutation_execution_strategy.rb:5:in `get_finished_value'
